### ISSUE TITLE
How to configure connection between mysql and redis?

### ISSUE THREAD

**Issue by SummerMagic** [adhocore/docker-lemp#23]
3306:3306?

**Comment by adhocore** [comment]
i dont think we should configure conn between mysql and redis
but rather application to mysql and application to redis

since all your stack including app is in single container docker, everything is local to you app
so db can be accessed at `127.0.0.1:3306` and redis at `127.0.0.1:6379`

for making db/redis available externally in host context, you can do a port mapping
```
ports:
  - 3306:3306
  - 6379:6379
```
where left part can be anything but right part must be intact
